name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to Github Registry 
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin
    - name: Build the Container image
      run: cd weechat-slack && docker build . --file Dockerfile --tag docker.pkg.github.com/${{ github.repository }}/weechat-slack:latest
    - name: Push image to Github Registry
      run: docker push docker.pkg.github.com/${{ github.repository }}/weechat-slack:latest
