---
name: Lint repo

on: [push]

jobs:

  build_matrix:

    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for changes
        id: diff
        run: |
          PRIMARY_BRANCH="master"
          CURRENT_COMMIT=$( git log --pretty=format:%H origin/$PRIMARY_BRANCH.. | head -n 1 )
          export DIFF=$( git diff --name-only origin/$PRIMARY_BRANCH $CURRENT_COMMIT )

          echo "$DIFF"

          echo "::set-output name=diff::$( echo "$DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )"

      - name: Set matrix for build
        id: build-matrix
        run: |
          DIFF="${{ steps.diff.outputs.diff }}"
          JSON="{\"include\":["

          while read path; do
            # Set $directory to substring before /
            image="$( echo $path | cut -d'/' -f1 -s )"

            if [ -z "$image" ]; then
              continue # Exclude root directory
            elif [ "$image" == .github ]; then
              continue # Exclude .github directory
            fi

            # Add build to the matrix only if it is not already included
            JSONline="{\"image\": \"$image\"},"
            if [[ "$JSON" != *"$JSONline"* ]]; then
              JSON="$JSON$JSONline"
            fi
          done <<< "$DIFF"

          # Remove last "," and add closing brackets
          if [[ $JSON == *, ]]; then
            JSON="${JSON%?}"
          fi
          JSON="$JSON]}"
          echo $JSON

          # Set output
          echo "::set-output name=matrix::$( echo "$JSON" )"

  lint:
    needs: build_matrix

    runs-on: ubuntu-latest

    strategy:
      matrix: ${{fromJson(needs.build_matrix.outputs.matrix)}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Lint ${{ matrix.image }}
        run: |
          docker run --rm -i \
            ghcr.io/hadolint/hadolint < ${{ matrix.image }}/Dockerfile
